### ISSUE TITLE
Todo List loses it's buttons when the FNEI mod is active

### ISSUE THREAD

**Issue by ChurchOrganist** [JonasJurczok/factorio-todo-list#135] opened 2019-03-16 16:50 UTC
Hi there,

I've just started a Yuoki playthrough on one of my servers.

We would very much like to use Todo List for our playthrough, but we have run into a problem.....

Todo List loses all the buttons at the bottom of its window when the FNEI mod is active (which we would also very much like to use).

I've informed the FNEI mod author via his GitHub page in the same manner as this.

Hopefully the two of you can come up with a solution.

Regards
Michael

PS you can reach him at https://github.com/npo6ka/FNEI but his Readme is in Russian :)

**Comment by JonasJurczok** [comment] 2019-03-16 17:00
Hi,
No worries, I already talked to him.

The problem is that with .17 the space for mods got decreased.


Just go to the mod settings and change the Todo list window height.

You can read the full discussion here:
https://mods.factorio.com/mod/Todo-List/discussion/5c7ba62ec3dad0000bfe86ed

Have fun :)

**Comment by JonasJurczok** [comment] 2019-07-09 20:30
Closing as it seems to be fixed.

**Closed by JonasJurczok** 2019-07-09 20:30 UTC
